/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'sans-serif'],
      },
      colors: {
        // Primitive Colors - Basis-Farben mit allen Abstufungen
        turquoise: {
          50: 'var(--color-muted-turquoise-50)',
          100: 'var(--color-muted-turquoise-100)',
          200: 'var(--color-muted-turquoise-200)',
          300: 'var(--color-muted-turquoise-300)',
          400: 'var(--color-muted-turquoise-400)',
          500: 'var(--color-muted-turquoise-500)',
          600: 'var(--color-muted-turquoise-600)',
          700: 'var(--color-muted-turquoise-700)',
          800: 'var(--color-muted-turquoise-800)',
          900: 'var(--color-muted-turquoise-900)',
          950: 'var(--color-muted-turquoise-950)',
        },
        gray: {
          50: 'var(--color-scooty-gray-50)',
          100: 'var(--color-scooty-gray-100)',
          200: 'var(--color-scooty-gray-200)',
          300: 'var(--color-scooty-gray-300)',
          400: 'var(--color-scooty-gray-400)',
          500: 'var(--color-scooty-gray-500)',
          600: 'var(--color-scooty-gray-600)',
          700: 'var(--color-scooty-gray-700)',
          800: 'var(--color-scooty-gray-800)',
          900: 'var(--color-scooty-gray-900)',
          950: 'var(--color-scooty-gray-950)',
        },
        white: {
          DEFAULT: 'var(--color-white)',
          50: 'var(--color-pure-white-50)',
          100: 'var(--color-pure-white-100)',
          200: 'var(--color-pure-white-200)',
          300: 'var(--color-pure-white-300)',
          400: 'var(--color-pure-white-400)',
          500: 'var(--color-pure-white-500)',
          600: 'var(--color-pure-white-600)',
          700: 'var(--color-pure-white-700)',
          800: 'var(--color-pure-white-800)',
          900: 'var(--color-pure-white-900)',
          950: 'var(--color-pure-white-950)',
        },
        black: 'var(--color-black)',
        lime: {
          50: 'var(--color-vivid-lime-50)',
          100: 'var(--color-vivid-lime-100)',
          200: 'var(--color-vivid-lime-200)',
          300: 'var(--color-vivid-lime-300)',
          400: 'var(--color-vivid-lime-400)',
          500: 'var(--color-vivid-lime-500)',
          600: 'var(--color-vivid-lime-600)',
          700: 'var(--color-vivid-lime-700)',
          800: 'var(--color-vivid-lime-800)',
          900: 'var(--color-vivid-lime-900)',
          950: 'var(--color-vivid-lime-950)',
        },
        red: {
          50: 'var(--color-bold-red-50)',
          100: 'var(--color-bold-red-100)',
          200: 'var(--color-bold-red-200)',
          300: 'var(--color-bold-red-300)',
          400: 'var(--color-bold-red-400)',
          500: 'var(--color-bold-red-500)',
          600: 'var(--color-bold-red-600)',
          700: 'var(--color-bold-red-700)',
          800: 'var(--color-bold-red-800)',
          900: 'var(--color-bold-red-900)',
          950: 'var(--color-bold-red-950)',
        },
        orange: {
          50: 'var(--color-bright-orange-50)',
          100: 'var(--color-bright-orange-100)',
          200: 'var(--color-bright-orange-200)',
          300: 'var(--color-bright-orange-300)',
          400: 'var(--color-bright-orange-400)',
          500: 'var(--color-bright-orange-500)',
          600: 'var(--color-bright-orange-600)',
          700: 'var(--color-bright-orange-700)',
          800: 'var(--color-bright-orange-800)',
          900: 'var(--color-bright-orange-900)',
          950: 'var(--color-bright-orange-950)',
        },
        blue: {
          50: 'var(--color-fresh-blue-50)',
          100: 'var(--color-fresh-blue-100)',
          200: 'var(--color-fresh-blue-200)',
          300: 'var(--color-fresh-blue-300)',
          400: 'var(--color-fresh-blue-400)',
          500: 'var(--color-fresh-blue-500)',
          600: 'var(--color-fresh-blue-600)',
          700: 'var(--color-fresh-blue-700)',
          800: 'var(--color-fresh-blue-800)',
          900: 'var(--color-fresh-blue-900)',
          950: 'var(--color-fresh-blue-950)',
        },
        fuchsia: {
          50: 'var(--color-toned-fuchsia-50)',
          100: 'var(--color-toned-fuchsia-100)',
          200: 'var(--color-toned-fuchsia-200)',
          300: 'var(--color-toned-fuchsia-300)',
          400: 'var(--color-toned-fuchsia-400)',
          500: 'var(--color-toned-fuchsia-500)',
          600: 'var(--color-toned-fuchsia-600)',
          700: 'var(--color-toned-fuchsia-700)',
          800: 'var(--color-toned-fuchsia-800)',
          900: 'var(--color-toned-fuchsia-900)',
          950: 'var(--color-toned-fuchsia-950)',
        },
        transparent: {
          full: 'var(--color-transparent-full)',
          'black-25': 'var(--color-transparent-black-25)',
          'black-50': 'var(--color-transparent-black-50)',
          'white-5': 'var(--color-transparent-white-5)',
          'white-10': 'var(--color-transparent-white-10)',
        },
        
        // Semantic Colors - Funktionale Tokens
        content: {
          text: {
            default: 'var(--color-content-text-default)',
            inverted: 'var(--color-content-text-inverted)',
            placeholder: 'var(--color-content-text-placeholder)',
            label: 'var(--color-content-text-label)',
            additional: 'var(--color-content-text-additional)',
            link: 'var(--color-content-text-link)',
            'link-clicked': 'var(--color-content-text-link-clicked)',
            disabled: 'var(--color-content-text-disabled)',
          },
        },
        background: {
          action: {
            'primary-subtle-default': 'var(--color-background-action-primary-subtle-default)',
            'primary-subtle-hover': 'var(--color-background-action-primary-subtle-hover)',
            'primary-subtle-pressed': 'var(--color-background-action-primary-subtle-pressed)',
            'primary-default': 'var(--color-background-action-primary-default)',
            'primary-hover': 'var(--color-background-action-primary-hover)',
            'primary-pressed': 'var(--color-background-action-primary-pressed)',
            'primary-focused': 'var(--color-background-action-primary-focused)',
            'secondary-default': 'var(--color-background-action-secondary-default)',
            'secondary-hover': 'var(--color-background-action-secondary-hover)',
            'secondary-pressed': 'var(--color-background-action-secondary-pressed)',
            'secondary-focused': 'var(--color-background-action-secondary-focused)',
            'tertiary-default': 'var(--color-background-action-tertiary-default)',
            'tertiary-hover': 'var(--color-background-action-tertiary-hover)',
            'tertiary-pressed': 'var(--color-background-action-tertiary-pressed)',
            'tertiary-focused': 'var(--color-background-action-tertiary-focused)',
             "disabled": 'var(--color-background-action-disabled)',
          },
        },
        
        // Component Colors - Button-spezifische Tokens
        button: {
          primary: {
            content: {
              default: 'var(--button-primary-color-content-default)',
              disabled: 'var(--button-primary-color-content-disabled)',
            },
            background: {
              'default-start': 'var(--button-primary-color-background-default-start)',
              'default-end': 'var(--button-primary-color-background-default-end)',
              'hover-start': 'var(--button-primary-color-background-hover-start)',
              'hover-end': 'var(--button-primary-color-background-hover-end)',
              'pressed-start': 'var(--button-primary-color-background-pressed-start)',
              'pressed-end': 'var(--button-primary-color-background-pressed-end)',
              'focused-start': 'var(--button-primary-color-background-focused-start)',
              'focused-end': 'var(--button-primary-color-background-focused-end)',
              disabled: 'var(--button-primary-color-background-disabled)',
            },
          },
        },

        // Header-spezifische Tokens
        header: {
          color: {
            content: {
              default: 'var(--header-color-content-default)',
            },
            border: {
              default: 'var(--header-color-border-default)',
            },
            background: {
              default: 'var(--header-color-background-default)',
              quiet: 'var(--header-color-background-quiet)',
            },
          },
        },
      },
      
      // Typography Tokens
      fontSize: {
        '11': 'var(--typography-font-size-11)',
        '12': 'var(--typography-font-size-12)',
        '13': 'var(--typography-font-size-13)',
        '14': 'var(--typography-font-size-14)',
        '16': 'var(--typography-font-size-16)',
        '18': 'var(--typography-font-size-18)',
        '19': 'var(--typography-font-size-19)',
        '22': 'var(--typography-font-size-22)',
        '23': 'var(--typography-font-size-23)',
        '27': 'var(--typography-font-size-27)',
        '28': 'var(--typography-font-size-28)',
        '33': 'var(--typography-font-size-33)',
        '35': 'var(--typography-font-size-35)',
        '39': 'var(--typography-font-size-39)',
        '43': 'var(--typography-font-size-43)',
        '47': 'var(--typography-font-size-47)',
        '54': 'var(--typography-font-size-54)',
        '68': 'var(--typography-font-size-68)',
      },
      fontWeight: {
        light: 'var(--typography-font-weight-light)',
        regular: 'var(--typography-font-weight-regular)',
        medium: 'var(--typography-font-weight-medium)',
        semibold: 'var(--typography-font-weight-semibold)',
        bold: 'var(--typography-font-weight-bold)',
      },
      lineHeight: {
        '12': 'var(--typography-line-height-12)',
        '14': 'var(--typography-line-height-14)',
        '17': 'var(--typography-line-height-17)',
        '18': 'var(--typography-line-height-18)',
        '21': 'var(--typography-line-height-21)',
        '25': 'var(--typography-line-height-25)',
        '30': 'var(--typography-line-height-30)',
        '36': 'var(--typography-line-height-36)',
        '37': 'var(--typography-line-height-37)',
        '44': 'var(--typography-line-height-44)',
        '45': 'var(--typography-line-height-45)',
        '53': 'var(--typography-line-height-53)',
        '56': 'var(--typography-line-height-56)',
        '63': 'var(--typography-line-height-63)',
        '70': 'var(--typography-line-height-70)',
        '76': 'var(--typography-line-height-76)',
        '87': 'var(--typography-line-height-87)',
        '109': 'var(--typography-line-height-109)',
      },
      letterSpacing: {
        '0': 'var(--typography-letter-spacing-0)',
      },
      
      // Spacing Tokens
      spacing: {
        '0': 'var(--spacing-0)',
        '2': 'var(--spacing-2)',
        '4': 'var(--spacing-4)',
        '8': 'var(--spacing-8)',
        '12': 'var(--spacing-12)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
        '32': 'var(--spacing-32)',
        '40': 'var(--spacing-40)',
        '48': 'var(--spacing-48)',
        '64': 'var(--spacing-64)',
        '80': 'var(--spacing-80)',
        'n-32': 'var(--spacing-n-32)',
        'n-24': 'var(--spacing-n-24)',
        'n-20': 'var(--spacing-n-20)',
        'n-16': 'var(--spacing-n-16)',
        'n-12': 'var(--spacing-n-12)',
        'n-8': 'var(--spacing-n-8)',
        'n-6': 'var(--spacing-n-6)',
        'n-4': 'var(--spacing-n-4)',
        'n-2': 'var(--spacing-n-2)',
      },
      
      // Border Tokens
      borderRadius: {
        '2': 'var(--border-radius-2)',
        '4': 'var(--border-radius-4)',
        '8': 'var(--border-radius-8)',
        '12': 'var(--border-radius-12)',
        '16': 'var(--border-radius-16)',
        '32': 'var(--border-radius-32)',
        'none': 'var(--border-radius-none)',
        'round': 'var(--border-radius-round)',
      },
      borderWidth: {
        '1': 'var(--border-width-1)',
        '2': 'var(--border-width-2)',
        '4': 'var(--border-width-4)',
        '8': 'var(--border-width-8)',
      },
      
      // Size Tokens
      width: {
        '16': 'var(--size-16)',
        '38': 'var(--size-38)',
      },
      height: {
        '16': 'var(--size-16)',
        '38': 'var(--size-38)',
      },
    },
  },
  plugins: [
    function({ addComponents }) {
      addComponents({
        '.typography-body-small': {
          'font-size': 'var(--typography-font-size-13)',
          'line-height': 'var(--typography-line-height-14)',
          'letter-spacing': 'var(--typography-letter-spacing-0)',
          'font-weight': 'var(--typography-font-weight-regular)',
          'font-family': 'Poppins, sans-serif',
        },
        '.typography-body-medium': {
          'font-size': 'var(--typography-font-size-16)',
          'line-height': 'var(--typography-line-height-25)',
          'letter-spacing': 'var(--typography-letter-spacing-0)',
          'font-weight': 'var(--typography-font-weight-regular)',
          'font-family': 'Poppins, sans-serif',
        },
        '.typography-heading-small': {
          'font-size': 'var(--typography-font-size-19)',
          'line-height': 'var(--typography-line-height-25)',
          'letter-spacing': 'var(--typography-letter-spacing-0)',
          'font-weight': 'var(--typography-font-weight-bold)',
          'font-family': 'Poppins, sans-serif',
        },
        '.typography-heading-small-emph': {
          'font-size': 'var(--typography-font-size-19)',
          'line-height': 'var(--typography-line-height-25)',
          'letter-spacing': 'var(--typography-letter-spacing-0)',
          'font-weight': 'var(--typography-font-weight-medium)',
          'font-family': 'Poppins, sans-serif',
        },
        '.typography-heading-medium': {
          'font-size': 'var(--typography-font-size-23)',
          'line-height': 'var(--typography-line-height-36)',
          'letter-spacing': 'var(--typography-letter-spacing-0)',
          'font-weight': 'var(--typography-font-weight-bold)',
          'font-family': 'Poppins, sans-serif',
        },
        '.typography-heading-large': {
          'font-size': 'var(--typography-font-size-28)',
          'line-height': 'var(--typography-line-height-44)',
          'letter-spacing': 'var(--typography-letter-spacing-0)',
          'font-weight': 'var(--typography-font-weight-bold)',
          'font-family': 'Poppins, sans-serif',
        },
      });
    },
  ],
}
